[build]
  command = "node scripts/create-env.js && npm run build:ssr"
  publish = "dist/bim-fellow-app/browser"

[build.environment]
  NODE_ENV = "production"

[build.secrets]
  secrets_scan_omit_keys = ["SERVICE_ID", "NOTIFICATION_TEMPLATE_ID", "RESPONSE_TEMPLATE_ID", "PUBLIC_KEY", "MAIL_BIMFELLOW"]
